Can one block of except statements handle multiple exception?
==>In Python, try-except blocks can be used to catch and respond to one or multiple exceptions. 
